# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
virtualenv:
  system_site_packages: false
before_install:
  - sudo apt-get install -y ninja-build build-essential nvidia-cuda-toolkit
addons:
  apt:
    update: true
matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py36" COVERAGE="true" LINT="false"
    - env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false" LINT="false"
    - env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py36" COVERAGE="false" LINT="true"
install:
  - source tests/travis_install.sh
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
script:
  - export NO_GPU_EXECUTION=1
  - pip install -e .
  - pip install tensorflow torch
  - if [[ "$LINT" == "false" ]]; then python setup.py test; fi
  - if [[ "$LINT" == "true" ]]; then flake8 src;python setup.py doctest; fi
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; codecov; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
